var data =[
	{'title':'华语频道','origin':'douban.fm','channel':'1'},
	{'title':'日语频道','origin':'douban.fm','channel':'17'},
	{'title':'韩语频道','origin':'douban.fm','channel':'18'},
	{'title':'法语频道','origin':'douban.fm','channel':'22'},
	{'title':'欧美频道','origin':'douban.fm','channel':'2'},
	{'title':'70年代频道','origin':'douban.fm','channel':'3'},
	{'title':'80年代频道','origin':'douban.fm','channel':'4'},
	{'title':'90年代频道','origin':'douban.fm','channel':'5'},
	{'title':'粤韵频道','origin':'douban.fm','channel':'6'},
	{'title':'民谣频道','origin':'douban.fm','channel':'8'},
	{'title':'轻音乐频道','origin':'douban.fm','channel':'9'},
	{'title':'电影原声频道','origin':'douban.fm','channel':'10'},
	{'title':'爵士频道','origin':'douban.fm','channel':'13'},
	{'title':'电子乐频道','origin':'douban.fm','channel':'14'},
	{'title':'说唱频道','origin':'douban.fm','channel':'15'},
	{'title':'R&B频道','origin':'douban.fm','channel':'16'},
	{'title':'蓝 频道','origin':'douban.fm','channel':'8'},
	{'title':'白 频道','origin':'bus.fm','channel':'1'},
	{'title':'灰 频道','origin':'bus.fm','channel':'2'},
	{'title':'黑 频道','origin':'bus.fm','channel':'3'},
	{'title':'红 频道','origin':'bus.fm','channel':'4'},
	{'title':'核弹 频道','origin':'douban.fm','channel':'1001698'},
	{'title':'摇滚-中国 频道','origin':'douban.fm','channel':'1000629'},
	{'title':'久石让频道','origin':'douban.fm','channel':'1001065'},
	{'title':'中国好声音频道','origin':'douban.fm','channel':'94'},
	{'title':'校园民谣频道','origin':'douban.fm','channel':'1002636'},
	{'title':'新歌主打频道','origin':'douban.fm','channel':'61'},
	{'title':'一句情歌频道','origin':'douban.fm','channel':'1000606'},
	{'title':'小清新频道','origin':'douban.fm','channel':'76'},
	{'title':'动漫频道','origin':'douban.fm','channel':'28'},
	{'title':'程序员之声','origin':'douban.fm','channel':'1001343'},
	{'title':'钢琴雕刻时光','origin':'douban.fm','channel':'1001061'},
	

	// {'title':'动漫频道','origin':'douban.fm','channel':'1'},
	// {'title':'动漫频道','origin':'douban.fm','channel':'1'},
	// {'title':'动漫频道','origin':'douban.fm','channel':'1'},
	// {'title':'动漫频道','origin':'douban.fm','channel':'1'},
	// {'title':'动漫频道','origin':'douban.fm','channel':'1'},
	// {'title':'动漫频道','origin':'douban.fm','channel':'1'}

	
];